# Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pareekshan?serverTimezone=UTC
    username: root
    password: Sumit@1998
    driver-class-name: com.mysql.cj.jdbc.Driver
---
# Hibernate JPA Configuration
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true